In [ ]:
import torch
import numpy as np
import pandas as pd
df = pd.read_csv("svt_dataset_10000.csv")
X = torch.tensor(df.values, dtype=torch.float32)

NameError: name 'pd' is not defined

اخد جزء فقط من مصفوفة

In [10]:
x = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(x[1:,1:])

tensor([[5, 6],
        [8, 9]])


هادي ايلا كنتي باغي تعرف عدد صفوف و الاعمدة


In [15]:
X = torch.tensor([
    [22., 190., 9., 98.],
    [45., 170., 8., 97.],
    [30., 80., 2., 99.],
     [30., 80., 2., 99.]
], dtype=torch.float32)
print(X.shape)

torch.Size([4, 4])


if i want to take one spesific column 


In [11]:
x = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(x[:,2])

tensor([3, 6, 9])


In [16]:
X = torch.tensor([
    [22., 190., 9., 98.],
    [45., 170., 8., 97.],
    [30., 80., 2., 99.],
     [30., 80., 2., 99.]
], dtype=torch.float32)
print(X.dim())

2


In [18]:
image_batch = torch.randn(32, 3, 224, 224)
print(image_batch)

tensor([[[[-1.1158e+00, -1.6610e-01,  1.4610e+00,  ...,  1.1540e+00,
            1.0606e+00,  9.4977e-01],
          [ 4.6895e-01, -7.6059e-02,  5.4517e-01,  ...,  1.7272e-01,
           -1.5363e+00,  1.4089e+00],
          [ 2.3999e-01,  2.2415e-01, -1.9951e-01,  ..., -1.5422e+00,
           -1.9607e+00, -5.3452e-01],
          ...,
          [ 5.1564e-01, -7.1880e-01, -1.1861e+00,  ...,  2.3761e-01,
           -1.1846e+00, -7.0204e-01],
          [-9.7573e-01, -6.1072e-01, -5.0702e-01,  ...,  1.2642e+00,
            3.1365e-01,  3.0125e-01],
          [ 3.6642e-01, -2.6170e+00,  1.0991e+00,  ..., -1.6830e+00,
           -1.5502e+00,  6.7568e-01]],

         [[ 1.0578e+00, -1.0631e+00, -2.1489e+00,  ...,  1.4709e+00,
            1.7178e-01, -2.7921e-01],
          [-3.0145e-01,  4.1214e-01, -3.6852e-01,  ..., -1.3182e-01,
            2.1578e-02, -3.4941e-01],
          [-5.5364e-01,  7.5113e-01, -6.9149e-01,  ...,  4.2876e-01,
            1.8841e-01, -1.4309e+00],
          ...,
     